---
title: "SSPS4102</br>Data Analytics in the Social Sciences"
subtitle: "Week 09</br>Hypothesis testing"
author: "Francesco Bailo"
institute: "The University of Sydney"
date: "Semester 1, 2023 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

background-image: url(https://upload.wikimedia.org/wikipedia/en/6/6a/Logo_of_the_University_of_Sydney.svg)
background-size: 95%

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r setup, include=FALSE}

options(htmltools.dir.version = FALSE)

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = 'svg', 
                      fig.width = 4, 
                      fig.height = 4, out.width="30%",
                      fig.align="center")

library(knitr)
library(kableExtra)
library(tidyverse)
library(sf)
library(DiagrammeR)
library(cowplot)
library(haven)

ggplot2::theme_set(theme_bw())

```

---

## Acknowledgement of Country

I would like to acknowledge the Traditional Owners of Australia and recognise their continuing connection to land, water and culture. The  University of Sydney is located on the land of the Gadigal people  of the Eora Nation. I pay my respects to their Elders, past and present.

---
class: inverse, center, middle

# A1 Feedback

---

## A1 Feedback (for A3)

* Always keep the focus of your report on **your** argument (what is going on?) and **your** voice (what **you** think is going on?, why?, how?). 

    1. Don't be all over the place: be selective with the (quantitative) information you present;
    
    2. Use quantitative information (analysis, results, figures, tables) to support your argument. Not the other way around.
    
    3. Don't introduce quantitative information that you can't explain and convincingly integrate into your argument. *A data report is not a list*. 
    
* For your A3, make sure two submit two files: 

  1. Your knitted documen (PDF, but DOCX is also fine if you prefer);
  
  2. A zip containing your project folder with your project files (at a minimum: .Rproj, .Rmd and data)

---